[package]
name = "mini_redis"
version = "0.1.0"
edition = "2024"

[dependencies]
mini_runtime = { path="../../mini_runtime" }
rt_entry = { path="../rt_entry" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
lazy_static = "1.4.0"
log = "0.4.20"
